rootProject.name = "syncforge"

include("core")
include("checksum")
include("compression")
include("path")
include("metadata")
include("validation")
include("serialization")
include("manifest")
include("scanner")
include("snapshot")
include("diff")
include("conflict")
include("patch")
include("planner")
include("runtime")
include("indexing")
include("query")
include("storage")
include("cli")
include("fuzz")
include("benchmark")
include("integration-tests")
