package com.syncforge.core.diagnostics;

import java.util.Objects;

/**
 * A Diagnostic represents a reported issue, warning, or informational message
 * generated by the SyncForge compiler, parser, validator, or execution stages.
 * It contains a severity level, error code, explanatory message, and an optional 
 * {@link SourceSpan} pointing to the source of the issue.
 * 
 * @param severity the severity level of this diagnostic. Must not be null.
 * @param code     the unique alphanumeric error or diagnostic code. Must not be null or blank.
 * @param message  the descriptive detail message. Must not be null or blank.
 * @param span     the source span detailing where the diagnostic occurs. May be null.
 */
public record Diagnostic(
        Severity severity,
        String code,
        String message,
        SourceSpan span
) {

    /**
     * Diagnostic severity levels.
     */
    public enum Severity {
        /**
         * Informational messages that do not affect compilation or execution.
         */
        INFO,

        /**
         * Warning messages indicating potential issues or sub-optimal configurations
         * that do not stop compilation or execution.
         */
        WARNING,

        /**
         * Hard errors that prevent successful validation, parsing, or execution.
         */
        ERROR
    }

    /**
     * Compact constructor to validate diagnostic parameters.
     *
     * @throws NullPointerException     if severity, code, or message is null.
     * @throws IllegalArgumentException if code or message is empty or blank.
     */
    public Diagnostic {
        Objects.requireNonNull(severity, "Severity must not be null");
        Objects.requireNonNull(code, "Diagnostic code must not be null");
        Objects.requireNonNull(message, "Diagnostic message must not be null");
        if (code.isBlank()) {
            throw new IllegalArgumentException("Diagnostic code must not be empty or blank");
        }
        if (message.isBlank()) {
            throw new IllegalArgumentException("Diagnostic message must not be empty or blank");
        }
    }

    /**
     * Returns a string representation of the diagnostic in a standardized format.
     * For example: {@code [ERROR] (SF001) Invalid character at manifest.sfm:1:12}
     *
     * @return a formatted string representing the diagnostic.
     */
    @Override
    public String toString() {
        String spanStr = span != null ? " at " + span : "";
        return "[" + severity + "] (" + code + ") " + message + spanStr;
    }
}
